[build]
  publish = "."

# Ensure HTML files are accessible without extension
[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200
